# Generated by Django 2.2.12 on 2020-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
