# Generated by Django 2.2.12 on 2020-05-10 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20200510_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='responseTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 13, 13, 27, 390474, tzinfo=utc), verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='webbanner',
            name='banner',
            field=models.ImageField(upload_to='Banner/%y/%m/%d/', validators=[mysite.models.validate_image], verbose_name='Banner'),
        ),
    ]
