# Generated by Django 2.2.12 on 2020-05-10 14:37

from django.db import migrations, models
import django.utils.timezone
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_auto_20200510_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='commendation',
            name='responseTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='webbanner',
            name='banner',
            field=models.ImageField(upload_to='Banner/%y/%m/%d/', validators=[mysite.models.validate_image], verbose_name='Banner'),
        ),
    ]
